### ISSUE TITLE
Console errors after installing 1.0.0-beta2

### ISSUE THREAD

**Issue by bjarnef** [bomortensen/Our.Umbraco.OpeningHours#11] opened 2016-07-18 22:11 UTC
After installing v1.0.0-beta2 in a Umbraco 7.4.3 installation I get the following:

![image](https://cloud.githubusercontent.com/assets/2919859/16932162/f1402f66-4d44-11e6-9dae-c9136e89ce44.png)

Debug is set to false.

![image](https://cloud.githubusercontent.com/assets/2919859/16932210/5034e41c-4d45-11e6-9c76-260869466a12.png)

**Comment by abjerner** [comment] 2016-07-19 06:24
@bjarnef Have you tried doing a hard refresh?

For `v1.0.0-beta2` the controller is now called `OpeningHours.Controllers.OpeningHoursController` (Pascal casing rather than camel casing), so it should just be a matter of refreshing the view in your browser.

https://github.com/bomortensen/Our.Umbraco.OpeningHours/blob/master/src/Our.Umbraco.OpeningHours/App_Plugins/OpeningHours/views/Editors/OpeningHours.html#L1

**Comment by bjarnef** [comment] 2016-07-21 13:10
@abjerner yes, hard refresh, recycle application pool, set debug to false.

but still having the issue. Also tried to increase client dependency version number.

This is the installed files via Umbraco package (.zip) - not NuGet.

~/OpeningHours/views/Editors/OpeningHours.html

![image](https://cloud.githubusercontent.com/assets/2919859/17023556/2a03ed04-4f54-11e6-9a99-b84991aebe1c.png)

~/OpeningHours/Controllers/OpeningHoursEditor.js
![image](https://cloud.githubusercontent.com/assets/2919859/17023666/bf4f94bc-4f54-11e6-8e13-1f1075aa7283.png)

I also have this file... hmm, not sure - I think it was from the old version and a installed the new one (upgraded).
~/OpeningHours/js/openingHours.controllers.js

package.manifest
![image](https://cloud.githubusercontent.com/assets/2919859/17023708/02337b68-4f55-11e6-82cf-a93ebe5de4af.png)

So it seems the Umbraco .zip file isn't up-to-date since the controller name in OpeningHours.html is `OpeningHours.html` ... but on Github it is PascalCase: https://github.com/bomortensen/Our.Umbraco.OpeningHours/blob/master/src/Our.Umbraco.OpeningHours/App_Plugins/OpeningHours/views/Editors/OpeningHours.html#L1

**Comment by abjerner** [comment] 2016-07-21 13:31
@bjarnef  Thanks for the update.

It seems that the Umbraco package contains both the old and new files for the cases the files were renamed to have another case. Filenames in a ZIP file are apparently case-sensitive, so `OpeningHours.html` is not the same as `openingHours.html`. Then things get interesting when extracting the ZIP on a Windows system.

All of this is most likely caused by an issue with by build job, so I need to look into that.

**Comment by bjarnef** [comment] 2016-07-21 13:55
Yes, uninstalled the package completely and installed it again, which e.g. contains the old file ~/OpeningHours/js/openingHours.controllers.js although not included in package.manifest.

**Comment by abjerner** [comment] 2016-09-10 19:30
Well ... vacation happened. And then coming back to work happened ... so I haven't really had time to work on this package for a while.

Anyways - I have now fixed the Grunt file so the Umbraco package is properly generated, and confirmed that this works in a fresh Umbraco 7.5.3 installation. Just to be sure - can you confirm this on your end as well?

**Comment by bjarnef** [comment] 2016-09-11 17:49
Hi Anders

I have tested beta3 and it now works in Umbraco 7.4.3

A minor thing I noticed is that the delete button in "holiday opening hours" doesn't use a pointer cursor, because it doesn't have `href` attribute.
You can add `href` and `prevent-default` attribute directive - or style `a[ng-click]`

**Comment by abjerner** [comment] 2016-09-15 20:31
@bjarnef Thanks. I hadn't noticed the missing `href` attribute - it is now fixed ;)

Also, closing the issue since the Grunt thing is now fixed.

**Closed by abjerner** 2016-09-15 20:31 UTC
